server:
  port: 8085
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/catalogue
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/catalogue
        registration:
          keycloak:
            authorization-grant-type: client_credentials
            scope:
              - metrics
            client-id: admin-service
            client-secret: XFzyTDGIQySZsGD4gz2kZyw6tXV5NDuE
          login:
            provider: keycloak
            scope:
              - metrics
              - openid
            client-id: admin-service
            client-secret: XFzyTDGIQySZsGD4gz2kZyw6tXV5NDuE