server:
  port: 8086
  forward-headers-strategy: framework
spring:
  application:
    name: catalogue-api-gateway
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      uri: http://config:config-password@localhost:8888