server:
  port: 8085
spring:
  cloud:
    config:
      enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/catalogue
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/catalogue
            user-name-attribute: preferred_username
        registration:
          keycloak:
            authorization-grant-type: client_credentials
            scope:
              - metrics
            client-id: admin-service
            client-secret: Ot6SR4T1raYQbs5CIU8thwsJq6S9LGk4
          login:
            provider: keycloak
            scope:
              - metrics
              - openid
            client-id: admin-service
            client-secret: Ot6SR4T1raYQbs5CIU8thwsJq6S9LGk4
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
eureka:
  client:
    enabled: false