server:
  forward-headers-strategy: native
  port: 8081
spring:
  application:
    name: selmag-catalogue-service
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      uri: http://config:config-password@172.17.0.1:8888