scrape_configs:
  - job_name: catalogue_config_server
    static_configs:
      - targets: [ "http://localhost:8888" ]
        labels:
          application: catalogue-config-server
    metrics_path: /actuator/prometheus
    oauth2:
      client_id: victoria-metrics
      client_secret: sq70kc2BS38MQZfLf3hKt8671TuCwLys
      token_url: http://localhost:8082/realms/catalogue/protocol/openid-connect/token
      scopes:
        - metrics
      endpoint_params:
        grant_type: client_credentials
  - job_name: catalogue_eureka_server
    static_configs:
      - targets: [ "http://localhost:8761" ]
        labels:
          application: catalogue-eureka-server
    metrics_path: /actuator/prometheus
    oauth2:
      client_id: victoria-metrics
      client_secret: sq70kc2BS38MQZfLf3hKt8671TuCwLys
      token_url: http://localhost:8082/realms/catalogue/protocol/openid-connect/token
      scopes:
        - metrics
      endpoint_params:
        grant_type: client_credentials
  - job_name: catalogue_api_gateway
    static_configs:
      - targets: [ "http://localhost:8086" ]
        labels:
          application: catalogue-api-gateway
    metrics_path: /actuator/prometheus
    oauth2:
      client_id: victoria-metrics
      client_secret: sq70kc2BS38MQZfLf3hKt8671TuCwLys
      token_url: http://localhost:8082/realms/catalogue/protocol/openid-connect/token
      scopes:
        - metrics
      endpoint_params:
        grant_type: client_credentials
  - job_name: catalogue_admin_service
    static_configs:
      - targets: ["http://localhost:8085"]
        labels:
          application: catalogue-admin-service
    metrics_path: /actuator/prometheus
    oauth2:
      client_id: victoria-metrics
      client_secret: sq70kc2BS38MQZfLf3hKt8671TuCwLys
      token_url: http://localhost:8082/realms/catalogue/protocol/openid-connect/token
      scopes:
        - metrics
      endpoint_params:
        grant_type: client_credentials
  - job_name: catalogue_catalogue_service
    static_configs:
      - targets: ["http://localhost:8081"]
        labels:
          application: catalogue-catalogue-service
    metrics_path: /actuator/prometheus
    oauth2:
      client_id: victoria-metrics
      client_secret: sq70kc2BS38MQZfLf3hKt8671TuCwLys
      token_url: http://localhost:8082/realms/catalogue/protocol/openid-connect/token
      scopes:
        - metrics
      endpoint_params:
        grant_type: client_credentials
  - job_name: catalogue_feedback_service
    static_configs:
      - targets: ["http://localhost:8084"]
        labels:
          application: catalogue-feedback-service
    metrics_path: /actuator/prometheus
    oauth2:
      client_id: victoria-metrics
      client_secret: sq70kc2BS38MQZfLf3hKt8671TuCwLys
      token_url: http://localhost:8082/realms/catalogue/protocol/openid-connect/token
      scopes:
        - metrics
      endpoint_params:
        grant_type: client_credentials
  - job_name: catalogue_customer_app
    static_configs:
      - targets: ["http://localhost:8083"]
        labels:
          application: catalogue-customer-app
    metrics_path: /actuator/prometheus
    oauth2:
      client_id: victoria-metrics
      client_secret: sq70kc2BS38MQZfLf3hKt8671TuCwLys
      token_url: http://localhost:8082/realms/catalogue/protocol/openid-connect/token
      scopes:
        - metrics
      endpoint_params:
        grant_type: client_credentials
  - job_name: catalogue_manager_app
    static_configs:
      - targets: ["http://localhost:8080"]
        labels:
          application: catalogue-manager-app
    metrics_path: /actuator/prometheus
    oauth2:
      client_id: victoria-metrics
      client_secret: sq70kc2BS38MQZfLf3hKt8671TuCwLys
      token_url: http://localhost:8082/realms/catalogue/protocol/openid-connect/token
      scopes:
        - metrics
      endpoint_params:
        grant_type: client_credentials