spring:
  datasource:
    url: jdbc:tc:postgresql:16:///selmag?TC_DAEMON=true
    username: selmag
    password: selmag
  boot:
    admin:
      client:
        enabled: false
  cloud:
    config:
      enabled: false
eureka:
  client:
    enabled: false