selmag:
  services:
    catalogue:
      uri: http://selmag-catalogue-service-svc.selmag.svc.cluster.local:8080
      registration-id: keycloak
server:
  forward-headers-strategy: native
  port: 8080
spring:
  application:
    name: selmag-manager-app
  boot:
    admin:
      client:
        enabled: true
        instance:
          service-host-type: ip
        url: http://selmag-admin-server-svc.selmag.svc.cluster.local:8080
  cloud:
    config:
      enabled: false
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://keycloak.selm.ag.192.168.49.2.nip.io/realms/selmag
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: manager-app-k8s
            client-secret: XSjDUQtDKFZfhdloStH8AY1Aphje0Yvm
            scope:
              - openid
              - view_catalogue
              - edit_catalogue
              - microprofile-jwt
          metrics:
            provider: keycloak
            client-id: manager-app-k8s
            client-secret: XSjDUQtDKFZfhdloStH8AY1Aphje0Yvm
            authorization-grant-type: client_credentials
            scope:
              - metrics_server
          discovery:
            provider: keycloak
            client-id: manager-app-k8s
            client-secret: XSjDUQtDKFZfhdloStH8AY1Aphje0Yvm
            authorization-grant-type: client_credentials
            scope:
              - discovery
      resourceserver:
        jwt:
          issuer-uri: http://keycloak.selm.ag.192.168.49.2.nip.io/realms/selmag
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  zipkin:
    tracing:
      endpoint: http://tempo-svc.selmag.svc.cluster.local:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
eureka:
  client:
    enabled: false