catalogue:
  services:
    catalogue:
      uri: http://localhost:8081
      registration-id: keycloak

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/manager
    username: manager
    password: pass
  jpa:
    properties.hibernate:
      batch_size: 50
      fetch_size: 50
      show_sql: true
      format_sql: true
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/catalogue
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: manager-app
            client-secret: yZ9TweALDKZaKFFAtRUqnrzKeisMmZCi
            scope:
              - openid
              - view_catalogue
              - edit_catalogue
              - microprofile-jwt