spring:
  boot:
    admin:
      client:
        enabled: false
  cloud:
    config:
      enabled: false
eureka:
  client:
    enabled: false
selmag:
  services:
    catalogue:
      uri: http://localhost:54321