server:
  port: 8888
spring:
  application:
    name: catalogue-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JavaCoDED78/Catalogue-config
          clone-on-start: true
          searchPaths: '{application}/{profile}'
          default-label: main
          timeout: 3
