server:
  port: 8888
spring:
  application:
    name: selmag-config-server
  cloud:
    config:
      server:
        native:
          search-locations: file://${user.home}/projects/2024/selmag-parent-sc24/config/cloud/{application}/{profile}