apiVersion: v1
kind: PersistentVolume
metadata:
  name: catalogue-db-pv
  labels:
    app: catalogue-db
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/lib/postgresql/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: catalogue-db-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue-db
  labels:
    app: catalogue-db
spec:
  selector:
    matchLabels:
      app: catalogue-db
  template:
    metadata:
      labels:
        app: catalogue-db
    spec:
      containers:
        - name: catalogue-db
          image: postgres:16
          env:
            - name: POSTGRES_DB
              value: catalogue
            - name: POSTGRES_USER
              value: catalogue
            - name: POSTGRES_PASSWORD
              value: catalogue
          ports:
            - containerPort: 5432
              name: postgresql
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresql-persistent-storage
      volumes:
        - name: postgresql-persistent-storage
          persistentVolumeClaim:
            claimName: catalogue-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue-db-svc
spec:
  ports:
    - port: 5432
  selector:
    app: catalogue-db
  clusterIP: None