eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            user-name-attribute: preferred_username
            issuer-uri: http://localhost:8082/realms/catalogue
        registration:
          keycloak:
            client-id: eureka-server
            client-secret: QjXwR66Jlgks8KzEkAuFMs45OsUqfo8Q
            scope:
              - openid
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/catalogue