spring:
  cloud:
    config:
      enabled: false
    gateway:
      routes:
        - id: catalogue-service-route
          uri: lb://catalogue-catalogue-service
          predicates:
            - Host=catalogue.api.127.0.0.1.nip.io
        - id: feedback-service-route
          uri: lb://catalogue-feedback-service
          predicates:
            - Host=feedback.api.127.0.0.1.nip.io
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/catalogue
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/catalogue
        registration:
          discovery:
            provider: keycloak
            client-id: api-gateway
            client-secret: 0DWDWru0l6ZFrsUAVfmtJy0p6dKhFnBy
            authorization-grant-type: client_credentials
            scope:
              - discovery
  application:
    name: catalogue-api-gateway
  boot:
    admin:
      client:
        enabled: false
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
server:
  port: 8086
  forward-headers-strategy: framework
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 1
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    registryFetchIntervalSeconds: 1