catalogue:
  services:
    catalogue:
      uri: lb://catalogue-catalogue-service
    feedback:
      uri: lb://catalogue-feedback-service
spring:
  boot:
    admin:
      client:
        enabled: false
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/catalogue
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: customer-app
            client-name: Catalogue Keycloak
            client-secret: GzILsArHTA7cIVf3uarPadYFEDozfNqW
            authorization-grant-type: authorization_code
            scope:
              - openid
              - view_catalogue
          metrics:
            provider: keycloak
            client-id: customer-app
            client-secret: GzILsArHTA7cIVf3uarPadYFEDozfNqW
            authorization-grant-type: client_credentials
            scope:
              - metrics_server
          discovery:
            provider: keycloak
            client-id: customer-app
            client-secret: GzILsArHTA7cIVf3uarPadYFEDozfNqW
            authorization-grant-type: client_credentials
            scope:
              - discovery
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/catalogue
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 1
    hostname: localhost
    client:
  client:
    service-url:
      registryFetchIntervalSeconds: 1
      defaultZone: http://localhost:8761/eureka/