server:
  port: 8888
spring:
  application:
    name: catalogue-config-server
  cloud:
    config:
      server:
        native:
          search-locations: file:///D:/Project/Catalogue/catalogue/config/cloud/{application}/{profile}