apiVersion: v1
kind: ConfigMap
metadata:
  name: manager-vmagent-cm
data:
  promscrape.yaml: |
    scrape_configs:
      - job_name: selmag_manager_app
        static_configs:
          - targets: ["http://localhost:8080"]
            labels:
              application: selmag-manager-app
        metrics_path: /actuator/prometheus
        oauth2:
          client_id: victoria-metrics
          client_secret: vTpeB59Sb2Qzh0HI4cXBlewm2ivY0dzD
          token_url: http://keycloak.selm.ag.192.168.49.2.nip.io/realms/selmag/protocol/openid-connect/token
          scopes:
            - metrics
          endpoint_params:
            grant_type: client_credentials
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selmag-manager-app-deployment
  labels:
    app: selmag-manager-app
spec:
  selector:
    matchLabels:
      app: selmag-manager-app
  template:
    metadata:
      labels:
        app: selmag-manager-app
    spec:
      volumes:
        - name: vmconfig
          configMap:
            name: manager-vmagent-cm
      containers:
        - name: selmag-manager-app
          image: 192.168.49.1:5000/selmag/manager-app:24.1.1
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: SPRING_PROFILES_ACTIVE
              value: cloudconfig,k8s
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config:config-password@selmag-config-server-svc.selmag.svc.cluster.local:8888
            - name: LOKI
              value: http://loki-svc.selmag.svc.cluster.local:3100
        - name: vmagent
          image: victoriametrics/vmagent:v1.93.12
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          args:
            - -promscrape.config=/etc/opt/vmagent/promscrape.yaml
            - -remoteWrite.url=http://vm-svc.selmag.svc.cluster.local:8428/api/v1/write
            - -remoteWrite.label=instance=$(NODE_NAME)
          volumeMounts:
            - mountPath: /etc/opt/vmagent
              name: vmconfig