server:
  port: 8083

catalogue:
  services:
    catalogue:
      uri: http://localhost:8081
    feedback:
      uri: http://localhost:8084

spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/catalogue
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: customer-app
            client-secret: iJcPJWyvbrkB9BEuwqkrAun9XKJFEI7l
            authorization-grant-type: authorization_code
            scope:
              - openid
              - view_catalogue